<template>
  <section id="Nosotros">
    <div class="container">
      <h2>Historia</h2>
      <div class="float-right mt-3 ml-3 mb-3">
        <img v-img:nos title="Descripción de la foto" src="https://via.placeholder.com/350x250/00BCD4/FFFFFF?text=Foto+I">
        <div class="text-center p-1 bg-info">Descripción de foto</div>
      </div>
      <p class="mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis nunc ut ligula consectetur, id finibus enim pulvinar. Nullam nec urna lorem. Etiam ut consectetur quam. Nam tempor nisl id pharetra luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent in ipsum et velit cursus pretium. Fusce consequat pellentesque hendrerit.</p>
      <p>Donec euismod leo ac turpis vehicula tempor. Fusce magna nulla, sagittis nec quam non, consequat bibendum nibh. Integer commodo, sem vel pretium aliquam, turpis metus mollis metus, et aliquam diam mi non tellus. Nam vehicula, nulla ac mollis cursus, metus quam rhoncus purus, et mollis arcu dolor sit amet enim. Morbi ultrices est eget scelerisque feugiat. Vivamus pellentesque orci a odio sagittis, a luctus eros molestie. Quisque quis nisl placerat, laoreet odio sollicitudin, consequat sapien. Aliquam egestas, velit vitae scelerisque dictum, urna dui lacinia ante, quis dignissim mauris ipsum a turpis.</p>
      <p>Cras congue tellus sed risus ornare consequat. Aenean pharetra rhoncus gravida. Donec arcu massa, rhoncus eget nulla sed, vehicula semper velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id ex eu elit blandit imperdiet eu ut ex. Curabitur dictum, augue ut tincidunt viverra, purus massa sollicitudin ex, eget placerat nibh mi at tortor. Duis vitae dolor non quam convallis egestas. Aliquam erat volutpat. Curabitur sed facilisis velit. Curabitur facilisis convallis mauris, in lacinia purus congue quis. Vivamus vestibulum vulputate neque, fermentum egestas tellus vehicula ut. Curabitur varius felis ac faucibus pretium. Curabitur cursus felis non sapien pulvinar, nec consequat libero aliquet. Cras vel dolor ligula. Sed tincidunt nisi a quam blandit fermentum.</p>
      <div class="float-left mr-3"><img v-img:nos src="https://via.placeholder.com/250x150/00BCD4/FFFFFF?text=Foto+II"></div>
      <p>Sed a placerat nunc. Donec ac facilisis nibh, non ornare ante. Maecenas non felis metus. Sed id semper ligula. Nulla tristique magna sit amet euismod cursus. Morbi sed nunc a diam bibendum convallis in vitae ex. In ipsum neque, tristique a mi ac, dignissim iaculis nunc. Ut at felis nec mauris sollicitudin tincidunt quis at metus.</p>
      <p>Quisque in nunc tempor, venenatis quam vitae, scelerisque ante. Curabitur in velit tincidunt, malesuada nulla at, rutrum mauris. Aliquam neque elit, imperdiet sed turpis et, tincidunt porta est. Proin a erat non dui ultrices gravida. Proin tincidunt quam ut luctus dictum. Curabitur malesuada erat id arcu tincidunt, quis congue est ornare. Vestibulum eget orci aliquam, tincidunt massa ac, varius elit. Maecenas et lobortis augue. In tempus egestas augue. Nulla tempor porttitor dignissim. Fusce ultrices, velit vitae commodo sagittis, lorem orci euismod elit, sed efficitur lacus nisl semper massa. Mauris egestas, neque sit amet ultrices vulputate, augue arcu vehicula justo, eu consectetur felis neque ac magna. Nam dictum consequat mauris, at elementum lorem laoreet vitae. Suspendisse interdum justo ac lobortis tincidunt. Integer eleifend scelerisque mi, vel aliquet velit. </p>
    </div>
  </section>
</template>